---
micronaut:
  application:
    name: hibernate

---
datasources:
  default:
    url: 'jdbc:mysql://localhost:3306/mydb'
    username: root
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
