---
micronaut:
  application:
    name: hibernate

---
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/mydb'
    username: root
    password: secret
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
